version: "3.8"

volumes:
  postgres_volume:

services:
  db:
    container_name: metric_db_repository
    image: postgres:14-alpine3.15
    environment:
      - "POSTGRES_DB=metrics-collection-service"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
    ports:
      - "5432:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data